Avoid command injection
418sec/node-prompt-here pull request #2
Opened 2020-08-21 21:00 UTC by alromh87

### 📊 Metadata *

Fixed command injection by cleaning dir before calling exec

#### Bounty URL: https://www.huntr.dev/bounties/1-npm-node-prompt-here

### ⚙️ Description *

Clean dir before calling exec

### 💻 Technical Description *

Disable command injection by replacing chars that can trigger new command

### 🐛 Proof of Concept (PoC) *

Code execution can be triggered with
promptHere.open('c:"; type nul > poc.txt "a');

![Captura de pantalla de 2020-08-21 22-06-46](https://user-images.githubusercontent.com/7505980/90934138-75c67380-e409-11ea-9c72-2720548d8a7d.png)

### 🔥 Proof of Fix (PoF) *

After Fix no code is executed so no file created
![Captura de pantalla de 2020-08-21 22-48-15](https://user-images.githubusercontent.com/7505980/90934658-5419bc00-e40a-11ea-9518-967ecf7d0faa.png)

### 👍 User Acceptance Testing (UAT)

Normal operation unafected
![Captura de pantalla de 2020-08-21 22-48-25](https://user-images.githubusercontent.com/7505980/90934693-6bf14000-e40a-11ea-9c78-60ab2b744fdf.png)

2020-08-22 08:49 UTC, Mik317 requested changes
The fix is `bypassable` since not all the `operators` are checked (like `||` or `-` and some other).
The following value of `dir` leads to `bypass` of the fix:

```js
dir = 'test || touch HACKED; \\'
```

Output: 

```js
> dir = 'test || type HACKED; \\'
'test || type HACKED; \\'
> require("fs").exists('HACKED', function(err, d){console.log(err, d)})
> false 
> cp = require('child_process')
{
  _forkChild: [Function: _forkChild],
  ChildProcess: [Function: ChildProcess],
  exec: [Function: exec],
  execFile: [Function: execFile],
  execFileSync: [Function: execFileSync],
  execSync: [Function: execSync],
  fork: [Function: fork],
  spawn: [Function: spawn],
  spawnSync: [Function: spawnSync]
}
> cp.exec('start "' + dir + '" /D "' + dir + '"')
ChildProcess {
  _events: [Object: null prototype] {
    close: [Function: exithandler],
    error: [Function: errorhandler]
  },
[..]
}
> require("fs").exists('HACKED', function(err, d){console.log(err, d)})
> true
> // File HACKED created successfully

```
I suggested to add some other checks to avoid `fix bypass` and/or `parameter injection` :smile:

Cheers,
Mik

2020-08-22 08:49 UTC, Mik317 commented on index.js
> +	dir = dir.replace(/"|;|&/g, '')
Better blacklist also common operators in case `"` could be bypassed with `\` in the first `dir` concatenated, like `||` and `-` (to avoid `parameter injection`) :smile:

2020-08-22 12:37 UTC, alromh87 commented on index.js
> +	dir = dir.replace(/"|;|&/g, '')
Thanks will improve it

2020-08-22 12:40 UTC, alromh87 commented
@Mik317 might be im using an old version of node, because I only had Xp at hand, but your POC doesn't seem to run in target system (Windows), works ok in Linux though.

Im using Node 5.12 on Win XP

2020-08-22 19:14 UTC, Mik317 commented
Hi @alromh87 :smile:,
I tried reproducing the issue on a real `windows` computer and not on my emulator in `Linux`.
It turns out to be right, the fix isn't bypassable as per my further tests. 

I saw also the comment on the other PR: for the same reason I was able to validate it using an emulator, but when checking directly on Win, it turned out to be invalid.

Also, I'm not sure if it's possible using something like https://stackoverflow.com/questions/54374379/how-to-lie-to-program-about-process-platform to bypass the check on a `linux` computer and lead to the bypass, so I would suggest you anyway to add the other `blacklisted` characters and I'll validate your fix :wink: !!!

I thank you for helping me spotting the irregularity and we hope to see many new disclosure/fixes by you :100: 

Cheers,
Mik

2020-08-22 20:20 UTC, alromh87 commented
Added other extra chars and test again also with platform override.

Glad to help

2020-08-22 20:39 UTC, Mik317 approved these changes
LGTM :smile: :tada:

Cheers,
Mik

2020-08-25 11:00 UTC, merged

2020-08-25 11:00 UTC, huntr-helper commented
Congratulations alromh87 - your fix has been selected! 🎉

Thanks for being part of the community & helping secure the world's open source code.
If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting!